version: '3.8'

services:
  frontend:
    build:
      context: ./hevent-fe
    container_name: vue-frontend
    ports:
      - '8081:80' 
    networks:
      - app-network

  backend:
    build:
      context: ./hevent-be
    container_name: spring-backend
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - '6379:6379'
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
